version: '3'
services:
  orion:
    extends:
      file: docker-compose-common-ld.yml
      service: orion
    depends_on:
    - mongo
  mongo:
    extends:
      file: docker-compose-common-ld.yml
      service: mongo
  crate:
    extends:
      file: docker-compose-common-ld.yml
      service: crate
  grafana:
    extends:
      file: docker-compose-common-ld.yml
      service: grafana
    depends_on:
    - crate
  redis:
    extends:
      file: docker-compose-common-ld.yml
      service: redis
  redis-commander:
    extends:
      file: docker-compose-common-ld.yml
      service: redis-commander
  timescale:
    extends:
      file: docker-compose-common-ld.yml
      service: timescale
  pgadmin:
    extends:
      file: docker-compose-common-ld.yml
      service: pgadmin
  quantumleap-db-setup:
    build: ../timescale-container/
    extends:
      file: docker-compose-common-ld.yml
      service: quantumleap-db-setup
    depends_on:
    - timescale
  quantumleap:
    extends:
      file: docker-compose-common-ld.yml
      service: quantumleap
    depends_on:
    - orion
    - timescale
    - redis
  quantumleap-wq:
    extends:
      file: docker-compose-common-ld.yml
      service: quantumleap-wq
    depends_on:
    - quantumleap
    - redis
    networks:
    - default
    - wqtests
volumes:
  mongodata: null
  cratedata: null
  redisdata: null
networks:
  default: null
  wqtests: null
