openapi: 3.0.0
info:
  title: E4C Electric Vehicle Charging System Data Models
  version: 1.0.0
  description: NGSI-LD data models for electric vehicle charging infrastructure

paths: {}

components:
  schemas:
    ChargingStation:
      $ref: "./removeRedundant/chargingStation_E4C.yaml#/ChargingStation"
    
    ChargingStationStatus:
      $ref: "./removeRedundant/chargingStationStatus_E4C.yaml#/ChargingStationStatus"
    
    ChargingPoint:
      $ref: "./removeRedundant/chargingPoint_E4C.yaml#/ChargingPoint"
    
    ChargingPointStatus:
      $ref: "./removeRedundant/chargingPointStatus_E4C.yaml#/ChargingPointStatus"
    
    E-Vehicle:
      $ref: "./removeRedundant/e-Vehicle_E4C.yaml#/E-Vehicle"
    
    E-VehicleStatus:
      $ref: "./removeRedundant/e-VehicleStatus_E4C.yaml#/E-VehicleStatus"

    ChargingSession:
      $ref: "./removeRedundant/chargingSession_E4C.yaml#/ChargingSession"